### PR TITLE
Fix ARMV6 detection.

### PR DESCRIPTION
**Pull request by daemonblade**

### CODE REVIEW

**Comment by jrmarino** [comment]
Before I merge, I have to ask if this will break existing releases of ARMv6 freebsd?
Or in other words, assuming this code was previously correct, what changed when?

**Comment by daemonblade** [comment]
The breakage happened after the imports from ravenadm. The "arch" string being passed to the detector functions were of the form "ARM      ".

I don't think that it has anything to do with the current armv6/armv7 changes to the the tree atm.

**Comment by jrmarino** [comment]
wait, what?
So the scenario is ravenports products are being used to build synth?
So wouldn't this change break synth built by freebsd ports (as it was designed to be?)
I think I'm even more confused now. :)

**Comment by daemonblade** [comment]
Sorry, I was unclear.

I think the point of breakage was the commit just prior to mine, with the comment:
> Import isolate_arch_from_file_type from ravenadm

However, I didn't have time to look at it until yesterday; a few months later.

**Comment by jrmarino** [comment]
oh right, I see now.
I forgot there was a comma in the ARM6 identifier, which is used as a string delimiter.
Good catch.

**Comment by jrmarino** [comment]
i would say it would be slightly more performant to compare raw strings e.g. "ARM           " rather than comparing the trimmed value.  Not sure if the impact is noticeable though

**Comment by daemonblade** [comment]
When I discovered the problem, I did think about counting the trailing whitespaces; but decided that trimming the result would be a more robust solution. As for the time taken to trim - it pales in significance to the port-builds.

However, it's no big deal to change the comparison test. Shall I prep a separate pull-request?

**Comment by jrmarino** [comment]
i think you can just append the PR by adding a commit to your repo.
Yeah, just remove the trim and set the "ARM" string to 11 characters (8 trailing spaces".  That should work fine.

**Pull request closed without merging**
